### ISSUE TITLE
Can't find theme-tomorrow.js

### ISSUE THREAD

**Issue by biver0** [opselo/darkRed#1]
Step 3:

 > location : 'node-red-folder/node_modules/node-red/public/vendor/ace/theme-tomorrow.js'

There is no node-red folder in the node_modules folder.
![Screenshot 2021-04-07 235212](https://user-images.githubusercontent.com/23388615/113981262-4def1900-97fc-11eb-8d03-d362930c5c79.png)

**Comment by opselo** [comment]
Please review the deprecation note.
There are now more modern methods to do this.
You can follow the link to the forum where other users are sharing these methods.
[A Dark-Theme for Node-RED here!](https://discourse.nodered.org/t/a-dark-theme-for-node-red-here)
Greetings.
